# Generated by Django 5.1.1 on 2024-09-19 20:06

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(blank=True, default='UTC', null=True),
        ),
    ]
