# Generated by Django 5.1.1 on 2024-09-18 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_department_alter_student_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name', 'email', '-level', '-added_at'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('email', 'matriculation_number', 'level')},
        ),
    ]
