# Generated by Django 5.1.1 on 2024-09-12 10:56

import apps.tokens.managers
import django.db.models.deletion
import django_otp.util
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentifierRelatedTOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=django_otp.util.random_hex, max_length=50, unique=True)),
                ('last_verified_counter', models.IntegerField(default=-1)),
                ('validity_period', models.IntegerField(default=1800)),
                ('length', models.IntegerField(default=6)),
                ('requestor_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('identifier', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Identifier Related Time Based OTP',
                'verbose_name_plural': 'Identifier Related Time Based OTPs',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', apps.tokens.managers.TimeBasedOTPManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserRelatedTOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=django_otp.util.random_hex, max_length=50, unique=True)),
                ('last_verified_counter', models.IntegerField(default=-1)),
                ('validity_period', models.IntegerField(default=1800)),
                ('length', models.IntegerField(default=6)),
                ('requestor_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totp', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Related Time Based OTP',
                'verbose_name_plural': 'User Related Time Based OTPs',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', apps.tokens.managers.TimeBasedOTPManager()),
            ],
        ),
    ]
