# Generated by Django 5.1.1 on 2024-09-18 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_starts', models.DateTimeField(blank=True, help_text='When is the next election scheduled to start?', null=True)),
                ('election_ends', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the office.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the office.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is the office active?')),
            ],
            options={
                'verbose_name_plural': 'Offices',
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the candidate.', max_length=255)),
                ('manifesto', models.TextField(blank=True, help_text='Manifesto of the candidate.', null=True)),
                ('disqualified', models.BooleanField(default=False, help_text='Is the candidate disqualified?')),
                ('office', models.ForeignKey(help_text='Office the candidate is contesting for.', on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.office')),
            ],
            options={
                'verbose_name_plural': 'Candidates',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True, help_text='Is the vote valid?')),
                ('candidate', models.ForeignKey(help_text='Candidate the vote is for.', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='elections.candidate')),
                ('voter', models.ForeignKey(help_text='Voter that cast the vote.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Votes',
            },
        ),
    ]
