# Generated by Django 5.1.1 on 2024-09-19 00:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ('name',), 'verbose_name_plural': 'Candidates'},
        ),
        migrations.AlterModelOptions(
            name='office',
            options={'ordering': ('name',), 'verbose_name_plural': 'Offices'},
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('candidate', 'voter')},
        ),
    ]
