# Generated by Django 5.1.1 on 2024-09-19 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_alter_candidate_options_alter_office_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField(help_text='When the election starts.')),
                ('end_date', models.DateTimeField(help_text='When the election ends.')),
            ],
            options={
                'verbose_name_plural': 'Elections',
                'ordering': ['-start_date', 'name', 'end_date'],
            },
        ),
        migrations.DeleteModel(
            name='ElectionConfig',
        ),
        migrations.AddField(
            model_name='office',
            name='election',
            field=models.ForeignKey(help_text='Election the office is being contested in.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='elections.election'),
        ),
    ]
