# Generated by Django 5.1.1 on 2024-09-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_election_delete_electionconfig_office_election'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the election.', null=True),
        ),
    ]
