# Generated by Django 5.1.1 on 2024-09-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_election_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='slug',
            field=models.SlugField(editable=False, help_text='Unique identifier for the election. Used in URLs.', unique=True),
        ),
    ]
