# Generated by Django 5.1.1 on 2024-09-20 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0006_alter_election_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='election',
            options={'ordering': ['-start_date', 'end_date', 'name'], 'verbose_name_plural': 'Elections'},
        ),
    ]
