# Generated by Django 5.1.1 on 2024-09-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0007_alter_election_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='is_valid',
        ),
        migrations.AddField(
            model_name='candidate',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='election',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='office',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
