# Generated by Django 5.1.1 on 2024-09-20 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0008_remove_vote_is_valid_candidate_added_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('election', models.ForeignKey(help_text='Election the vote lock is for.', on_delete=django.db.models.deletion.CASCADE, related_name='vote_locks', to='elections.election')),
                ('voter', models.ForeignKey(help_text='Voter that is locked.', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vote Locks',
                'unique_together': {('election', 'voter')},
            },
        ),
    ]
